<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CFIPOpeningRangeManipulation</AssemblyName>
    <AlgoName>CFIP Opening Range Manipulation</AlgoName>
    <RootNamespace>cAlgo</RootNamespace>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.21" />
  </ItemGroup>
</Project>
