<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CFIP.Indicator.CI</AssemblyName>
    <RootNamespace>cAlgo</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.21" />
    <PackageReference Include="Skender.Stock.Indicators" Version="2.7.3" />
    <ProjectReference Include="../../src/CFIP.Contracts/CFIP.Contracts.csproj" />
    <Compile
      Include="../../src/CFIP.Indicator/**/*.cs"
      Exclude="../../src/CFIP.Indicator/**/bin/**;../../src/CFIP.Indicator/**/obj/**" />
  </ItemGroup>
</Project>