namespace CFIP.Contracts
{
    public sealed record PlanSnapshot(
        double Entry,
        double IdealEntry,
        double EntryZoneLow,
        double EntryZoneHigh,
        double EntryTrigger,
        double EntryInvalidation,
        double Stop,
        double Tp1,
        double Tp2,
        double Tp3,
        double Tp4,
        double PlanRisk,
        double Tp1Rr,
        double Tp2Rr,
        double Tp3Rr,
        double Tp4Rr,
        int EntryQuality,
        int PlanQuality,
        int StopQuality,
        int Tp1Quality,
        int Tp2Quality,
        int Tp3Quality,
        int Tp4Quality,
        int HtfTargetCount,
        string EntrySource,
        string StopSource,
        string Tp1Source,
        string Tp2Source,
        string Tp3Source,
        string Tp4Source,
        string AnalyticalReason);
}
