<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CFIP.Indicator</AssemblyName>
    <RootNamespace>cAlgo</RootNamespace>
    <Deterministic>true</Deterministic>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <CAlgoApiPath Condition="'$(CFIP_CTRADER_API)' != ''">$(CFIP_CTRADER_API)</CAlgoApiPath>
    <CAlgoApiPath Condition="'$(CFIP_CTRADER_API)' == ''">$(UserProfile)\Documents\cAlgo\API\cAlgo.API.dll</CAlgoApiPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Skender.Stock.Indicators" Version="2.7.3" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="cAlgo.API">
      <HintPath>$(CAlgoApiPath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
