<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CFIPIndicator</AssemblyName>
    <AlgoName>CFIP-Smart-Indicator</AlgoName>
    <RootNamespace>cAlgo</RootNamespace>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.21" />
    <PackageReference Include="Skender.Stock.Indicators" Version="2.7.3" />
    <ProjectReference Include="..\CFIP.Contracts\CFIP.Contracts.csproj" />
  </ItemGroup>
</Project>
