using System;
using System.Collections.Generic;
using System.Linq;
using cAlgo.API;
using cAlgo.API.Indicators;
using cAlgo.API.Internals;

namespace cAlgo
{
    internal sealed class Frame
                    {
                        public Bars Bars;
                        public int Index;
                        public double Atr;
                        public double Rsi;
                        public bool NativeIndicatorsReady;
                        public double Adx;
                        public double EmaFast;
                        public double EmaSlow;
                        public int Direction;
                        public int BullScore;
                        public int BearScore;
                        public int Evidence;
                        public int Quality;
                        public bool StructureBull;
                        public bool StructureBear;
                        public bool MssBull;
                        public bool MssBear;
                        public bool ChochBull;
                        public bool ChochBear;
                        public bool DisplacementBull;
                        public bool DisplacementBear;
                        public bool LiquidityBull;
                        public bool LiquidityBear;
                        public bool FvgBull;
                        public bool FvgBear;
                        public int FvgBullQuality;
                        public int FvgBearQuality;
                        public bool ObBull;
                        public bool ObBear;
                        public int ObBullQuality;
                        public int ObBearQuality;
                        public bool FvgObBullConfluence;
                        public bool FvgObBearConfluence;
                        public int LocationEvidenceBull;
                        public int LocationEvidenceBear;
                        public int LocationEvidenceBullCount;
                        public int LocationEvidenceBearCount;
                        public bool TrendBull;
                        public bool TrendBear;
                        public bool MomentumBull;
                        public bool MomentumBear;
                        public bool RejectionBull;
                        public bool RejectionBear;
                        public bool EqualHigh;
                        public bool EqualLow;
                        public bool VolumeBull;
                        public bool VolumeBear;
                        public bool MacdBull;
                        public bool MacdBear;
                        public bool VwapBull;
                        public bool VwapBear;
                        public bool VolatilityBull;
                        public bool VolatilityBear;
                        public bool Choppy;
                        public double Choppiness;
                        public int IndicatorConfluenceQuality;
                        public int IndicatorConflict;
                        public int IndicatorIndependentEvidenceGroupCount;
                        public double AtrRatio;
                        public double EmaSpreadAtr;
                        public double EmaSlopeAtr;
                        public double RangeEfficiency;
                        public string Regime;
                        public int RegimeQuality;
                        public int RegimeStability;
                        public string PreviousRegime;
                        public string RegimeTransition;
                        public int OssBullVotes;
                        public int OssBearVotes;
                        public int OssIndicatorCount;
                        public bool OssBull;
                        public bool OssBear;
                        public double WaveTrend;
                        public double WaveTrendSignal;
                        public double WaveTrendHistogram;
                        public double WaveTrendPrevious;
                        public double WaveTrendSignalPrevious;
                        public double WaveTrendDelta;
                        public int WaveTrendQuality;
                        public int WaveTrendDirection;
                        public bool WaveTrendBull;
                        public bool WaveTrendBear;
                        public bool WaveTrendBullCross;
                        public bool WaveTrendBearCross;
                        public bool WaveTrendAboveZero;
                        public bool WaveTrendBelowZero;
                        public bool WaveTrendOversold;
                        public bool WaveTrendOverbought;
                        public int DivergenceDirection;
                        public int DivergenceQuality;
                        public string DivergenceType;
                        public bool RegularDivergenceBull;
                        public bool RegularDivergenceBear;
                        public bool HiddenDivergenceBull;
                        public bool HiddenDivergenceBear;
                    }
}
