<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CFIP.cBot</AssemblyName>
    <RootNamespace>CFIP.cBot</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.21" />
    <ProjectReference Include="..CFIP.ContractsCFIP.Contracts.csproj" />
  </ItemGroup>
</Project>
